version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    environment:
      STAGE: 'production'
      DOMAINS: 'h-l33t.site -> http://web'
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
